name: Python CI

on:
  push:
    branches:
      
main

jobs:
  test:

    runs-on: ubuntu-latest

    steps:

      
name: Repository herunterladen
      uses: actions/checkout@v4

      
name: Python installieren
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

      
name: Tests ausführen
      run: python tests.py
